services:
  - type: web
    name: popcorn-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python python_telegram_bot.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OMDB_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://movieagent2-5.onrender.com
    port: 8080 